# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('instructions', models.TextField(blank=True, default='', null=True)),
                ('source', models.TextField(blank=True, default='', null=True)),
                ('ingredients', models.ManyToManyField(to='api.Ingredient')),
            ],
        ),
    ]
